### PR TITLE
(fix): Switch React API from v17 to v18

### LINKED ISSUE #167: React v18 warns about changed API
https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis

Screenshot 2023-07-12 at 3 12 59 PM

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes #167
Screenshot 2023-07-12 at 3 16 50 PM

### CODE REVIEW

File: src/ui.tsx [hunk 1]
```diff
@@ -1190,7 +1190,10 @@ function DragTarget() {
   </div>;
 }
 
-ReactDOM.render(<Root />, document.getElementById("app"));
+const container = document.getElementById("app");
+// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+const root = createRoot(container!);
+root.render(<Root />);
```
Comment (nornagon) [inline src/ui.tsx:1196]: I prefer the point-free style most of the time, so I'll nitpick this to
```suggestion
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
createRoot(document.getElementById("app")!).render(<Root />);
```

**Review by nornagon — APPROVED** [review]

File: src/ui.tsx (hunk 1 above)
Comment (alexrudd2) [reply src/ui.tsx]: Fine with me, I was just following React docs.
